### ISSUE TITLE
Latest Ember CLI breaks addon

### ISSUE THREAD

**Issue by gte451f** [tylergaw/ember-cli-chartist#40]
Upgrading from Ember CLI 0.2.7 to...1.13.1 causes Ember Chartist to barf out an error....

```
Path or pattern "bower_components/chartist/dist/chartist.js" did not match any files
Error: Path or pattern "bower_components/chartist/dist/chartist.js" did not match any files
    at Object.multiGlob (/my-code/test-project/node_modules/ember-cli/node_modules/broccoli-kitchen-sink-helpers/index.js:203:13)
    at Class.module.exports.CachingWriter.extend.addFiles (/my-code/test-project/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/concat-with-maps.js:74:13)
    at Class.module.exports.CachingWriter.extend.updateCache (/my-code/test-project/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/concat-with-maps.js:52:12)
    at /my-code/test-project/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/index.js:92:34
    at lib$rsvp$$internal$$tryCatch (/my-code/test-project/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/my-code/test-project/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/my-code/test-project/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:472:11)
    at lib$rsvp$asap$$flush (/my-code/test-project/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1290:9)
    at process._tickCallback (node.js:355:11)
```

Removing the addon restores normal functionality to the ember project.

**Comment by tylergaw** [comment]
Thanks @gte451f. I'm guessing this is at least partially due to the transition from using `Brocfile.js` to `ember-cli-build.js` as described here https://github.com/ember-cli/ember-cli/blob/master/TRANSITION.md

Will take a look soon.

**Comment by caseyjenks** [comment]
I'm also getting this error on Ember CLI 0.2.5. Any ideas?

**Comment by tylergaw** [comment]
@caseyjenks @gte451f I have a beta tag that I think fixes this https://github.com/tylergaw/ember-cli-chartist/tree/v0.3.0-beta1 wanna give that a try?

**Comment by gte451f** [comment]
I am new to this so I might have done this wrong but I'm still getting the same error.

Steps I followed to try w/ Beta release:

1. Install Package
    npm install ember-cli-chartist --save-dev

1. Update package.json w/ beta release
`"ember-cli-chartist": "^0.2.9",`
becomes...
`"ember-cli-chartist": "v0.3.0-beta1",`

1. Install new package
`npm install;`

1. Run Ember
`ember server`


Ember CLI Release 1.13.1

**Comment by tylergaw** [comment]
@gte451f Sorry, I missed updated the install docs. In the Beta version, we're now installing the chartist dep in the blueprint here https://github.com/tylergaw/ember-cli-chartist/blob/v0.3.0-beta1/blueprints/ember-cli-chartist/index.js#L11

I found this out recently too, but that means ember-cli-chartist needs to be installed with `ember install ember-cli-chartist` instead of `npm install`. At least for the initial install. If not, the chartist dependency is not installed.

This feels a bit clunky still, but give that a try and see if it works for you.

**Comment by gte451f** [comment]
Well, I removed the addon from package.json and re-installed via:
`install ember-cli-chartist`
...and everything just worked. 

I did not need to test out the beta, 0.2.9 worked just like that!
